---
title: "Catalog of `babel` causes and conditions"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
options(scipen = '999')
```

```{r}
# Load packages and WHO VA instrument
library(tidyverse)
library(flextable)

# this catalogs how conditions are recorded in various babel translations
# start by loading master babel file:
babel <- read_csv("../vida/data-raw/babel.csv")
```

## Fever

```{r results='asis'}
fever <- babel[ grep("fever",babel$question_full), ]
for(level in levels(as.factor(fever$format))) {
  df <- fever %>% 
    filter(format == level) %>%
    select(variable:country, question_full) 
  print( knitr::kable(df, caption=paste0("Format: ",level) ) )
  ft <- df %>%
    flextable() %>%
    set_caption(level) %>%
    autofit()
  flextable_to_rmd(ft)
}
```


