---
title: "VIDA: Causes of death for children"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message=FALSE,
                      warning=FALSE)

library(tidyverse)
library(flextable)
library(knitr)
library(kableExtra)
# source("kalter_child.R")
source("liu_child.R")
```

# EAVA algorithm 

Expert Algorithm for Verbal Autopsy (EAVA) based on

> Kalter et al., [Direct estimates of national neonatal and child cause–specific mortality proportions in Niger by expert algorithm and physician–coded analysis of verbal autopsy interviews](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4416334/), J Glob Health. 2015 Jun; 5(1): 010415

# Results for Mali data

```{r}
df <- read_csv("data/mali_babel/CHAMPS_Verbal_Autopsy_Form_results_babel.csv")
causes <- get_causes(df, format="champs2")
causes <- data.frame( Cause = causes )
causes %>% 
  group_by(Cause) %>% 
  tally %>% 
  regulartable() %>% 
  theme_zebra() %>% 
  set_caption("CHAMPS_Verbal_Autopsy_Form_results.csv") %>% 
  autofit()

# regulartable( cbind( death_dates(df, format="champs2"), interview_dates(df, format="champs2") ) ) %>% 
#   autofit()

ages <- get_ages(df, "champs2") 
summary(ages)
summary( ages - df$age_days )
df$date_death_deceased
df$date_birth_deceased
# ALL GOOD!

```

```{r}
df <- read_csv("data/mali_babel/CHAMPS_Verbal_Autopsy_Form_v2_04_1_results_babel.csv")
causes <- get_causes( df, format="champs2")
causes <- data.frame( Cause = causes )
causes %>% 
  group_by(Cause) %>% 
  tally %>% 
  regulartable() %>% 
  theme_zebra() %>% 
  set_caption("CHAMPS_Verbal_Autopsy_Form_v2_04_1_results.csv") %>% 
  autofit()

# regulartable( cbind( death_dates(df, format="champs2"), interview_dates(df, format="champs2") ) ) %>% 
#   autofit()

ages <- get_ages(df, "champs2") 
summary(ages)
summary( ages - df$age_days )
df$date_death_deceased
df$date_birth_deceased
# ALL GOOD!

```

```{r}
df <- read_csv("data/mali_babel/CHAMPS_Verbal_Autopsy_Form_v2_04_results_babel.csv")
causes <- get_causes( df, format="champs2")
causes <- data.frame( Cause = causes )
causes %>% 
  group_by(Cause) %>% 
  tally %>% 
  regulartable() %>% 
  theme_zebra() %>% 
  set_caption("CHAMPS_Verbal_Autopsy_Form_v2_04_results.csv") %>% 
  autofit()

# regulartable( cbind( death_dates(df, format="champs2"), interview_dates(df, format="champs2") ) ) %>% 
#   autofit()

ages <- get_ages(df, "champs2") 
summary(ages)
summary( ages - df$age_days )
summary( ages - df$age)
df$date_death_deceased
df$date_birth_deceased
# NOT GOOD! ages bad but df$age_days seems fine

```

```{r}
df <- read_csv("data/mali_babel/VA_Death_of_a_child_under_4_weeks_to_59_months_results_21MAR2018_babel.csv")
causes <- get_causes( df, format="champs1")
causes <- data.frame( Cause = causes )
causes %>% 
  group_by(Cause) %>% 
  tally %>% 
  regulartable() %>% 
  theme_zebra() %>% 
  set_caption("VA_Death_of_a_child_under_4_weeks_to_59_months_results_21MAR2018.csv") %>% 
  autofit()

# regulartable( cbind( death_dates(df, format="champs1"), interview_dates(df, format="champs1") ) ) %>% 
#   autofit()

ages <- get_ages(df, "champs1") 
summary(ages)
summary( ages - df$age_days )
summary( ages - df$age)
df$date_death_deceased
df$date_birth_deceased
# NOT GOOD! ages bad and df has neither age_days nor age variable

```

# Results for Gambia data

## BN HDSS 

```{r}
df <- read_csv("data/gambia_babel/bn_hdss/VA_Child_WHO2016_babel.csv")
causes <- get_causes( df, format="c16")
causes <- data.frame( Cause = causes )
causes %>% 
  group_by(Cause) %>% 
  tally %>% 
  regulartable() %>% 
  theme_zebra() %>% 
  set_caption("VA_Child_WHO2016.csv") %>% 
  autofit()

# regulartable( cbind( death_dates(df, format="c16"), interview_dates(df, format="c16") ) ) %>% 
#   autofit()

ages <- get_ages(df, "c16") 
summary(ages)
summary( ages - df$age_days )
summary( ages - df$age)
df$date_death_deceased
df$date_birth_deceased
# ages seems fine, but df has no age_days variable
# and df$age is totally jacked up

```

```{r}
df <- read_csv("data/gambia_babel/bn_hdss/VA_ChildForm_WHO2012_babel.csv")
causes <- get_causes( df, format="c12_16")
causes <- data.frame( Cause = causes )
causes %>% 
  group_by(Cause) %>% 
  tally %>% 
  regulartable() %>% 
  theme_zebra() %>% 
  set_caption("VA_ChildForm_WHO2012.csv") %>% 
  autofit()

# regulartable( cbind( death_dates(df, format="c12_16"), interview_dates(df, format="c12_16") ) ) %>% 
#   autofit()

ages <- get_ages(df, "c12_16") 
summary(ages)
summary( ages - df$age_days )
summary( ages - df$age)
df$date_death_deceased
df$date_birth_deceased

# someone born in 1957?? see ages[65], df$date_birth_deceased[65], df$date_death_deceased[65]
```

## BS HDSS 

```{r}
df <- read_csv("data/gambia_babel/bs_hdss/VA_Child_Indepth_2008-2012_clean duration_babel.csv")
causes <- get_causes( df, format="c08_12")
causes <- data.frame( Cause = causes )
causes %>% 
  group_by(Cause) %>% 
  tally %>% 
  regulartable() %>% 
  theme_zebra() %>% 
  set_caption("VA_Child_Indepth_2008-2012_clean duration.csv") %>% 
  autofit()

ages <- get_ages(df, "c08_12") 
summary(ages)
summary( ages - df$age_days )
summary( ages - df$age)
df$date_death_deceased
df$date_birth_deceased
# NOT GOOD! no date_birth_deceased variable; many many NAs in date_death_deceased

```


```{r}
df <- read_csv("data/gambia_babel/bs_hdss/VA_Child_Indepth_2008-2012_babel.csv")
causes <- get_causes( df, format="c08_12")
causes <- data.frame( Cause = causes )
causes %>% 
  group_by(Cause) %>% 
  tally %>% 
  regulartable() %>% 
  theme_zebra() %>% 
  set_caption("VA_Child_Indepth_2008-2012.csv") %>% 
  autofit()

ages <- get_ages(df, "c08_12") 
summary(ages)
summary( ages - df$age_days )
summary( ages - df$age)
df$date_death_deceased
df$date_birth_deceased
# NOT GOOD! no date_birth_deceased variable; many many NAs in date_death_deceased

```


```{r}
df <- read_csv("data/gambia_babel/bs_hdss/VA_Child_WHO2012-mid 2016_babel.csv")
causes <- get_causes( df, format="c12_16")
causes <- data.frame( Cause = causes )
causes %>% 
  group_by(Cause) %>% 
  tally %>% 
  regulartable() %>% 
  theme_zebra() %>% 
  set_caption("VA_Child_WHO2012-mid 2016.csv") %>% 
  autofit()

# regulartable( cbind( death_dates(df, format="c12_16"), interview_dates(df, format="c12_16") ) ) %>% 
#   autofit()

ages <- get_ages(df, "c12_16") 
summary(ages)
summary( ages - df$age_days )
summary( ages - df$age)
df$date_death_deceased
df$date_birth_deceased
# ages seems okay; no df$age_days or df$age

```


```{r}
df <- read_csv("data/gambia_babel/bs_hdss/VA_Child_WHO2016_babel.csv")
causes <- get_causes( df, format="c16")
causes <- data.frame( Cause = causes )
causes %>% 
  group_by(Cause) %>% 
  tally %>% 
  regulartable() %>% 
  theme_zebra() %>% 
  set_caption("VA_Child_WHO2016.csv") %>% 
  autofit()

# regulartable( cbind( death_dates(df, format="c16"), interview_dates(df, format="c16") ) ) %>% 
#   autofit()

ages <- get_ages(df, "c16") 
summary(ages)
summary( ages - df$age_days )
summary( ages - df$age)
df$date_death_deceased
df$date_birth_deceased
# NOT GOOD! many negative ages... quite a few typos in dates

```

