
conditions <- list()
conditions[["Neonatal tetanus"]] <- c("convulsion","spasm","suckl","cry")
conditions[["Congenital malformation"]] <- c("malform")
conditions[["Birth asphyxia"]] <- c("cry","breath","suck","convulsion","letharg")
conditions[["Birth injury"]] <- c("bruise","injury","sign")
conditions[["Preterm delivery with respiratory distress syndrome"]] <- c("pregnancy","duration","breathing","fever","cold")
conditions[["Meningitis"]] <- c("fever","fontanelle","convulsion","letharg","unconscious","unresponsive")
conditions[["Diarrhea"]] <- c("diarrhea","stool")
conditions[["Pneumonia"]] <- c("cough","breathing","chest","grunt","cry")
conditions[["Possible diarrhea"]] <- c("diarrhea","stool","fever","cold","suck","convulsion","vomit","letharg","unconscious","chest","grunt")
conditions[["Possible pneumonia"]] <- c("breathing","fever","cold","suck","convulsion","vomit","letharg","unconscious","chest","grunt")
conditions[["Sepsis"]] <- c("fever","cold","suck","convulsion","vomit","letharg","unconscious","chest","grunt")
conditions[["Neonatal jaundice"]] <- c("yellow","suck","letharg","unconscious","unresponsive","fever","hypothermia")
conditions[["Neonatal hemorrhagic syndrome"]] <- c("bleed","bled","fever","cold")
conditions[["Sudden unexplained death"]] <- c("sudden","ill","symptom","sign")
conditions[["Preterm delivery"]] <- c("pregnancy","duration")

# save(conditions, file="kalter.RData")
