
conditions <- list()
conditions[["Interview"]] <- c("visit","nterview","date","age","Date")
conditions[["Injury"]] <- c("accident","fall","drown","poison","bite","sting","burn","violence","injury")
conditions[["AIDS"]] <- c("swell","armpit","rash","mouth", "tongue","thin","protruding","diarrhea","stool","fever","breathing","chest")
conditions[["Malnutrition (underlying)"]] <- c("thin","swell")
conditions[["Measles"]] <- c("date","age","Date","rash","fever","face")
conditions[["Meningitis"]] <- c("fever","neck","fontanelle")
conditions[["Dysentery"]] <- c("diarrhea","stool")
conditions[["Diarrhea"]] <- c("diarrhea","stool")
conditions[["Pertussis"]] <- c("cough","vomit","stridor")
conditions[["Pneumonia"]] <- c("cough","breathing","chest","grunt")
conditions[["Malaria"]] <- c("fever","neck","fontanelle","pallor","breathing","convulsion","unconscious")
conditions[["Possible dysentery"]] <- c("diarrhea","stool","fever","convulsion","unconscious")
conditions[["Possible diarrhea"]] <- c("diarrhea","stool","fever","convulsion","unconscious")
conditions[["Possible pneumonia"]] <- c("cough","breathing","chest","stridor","grunt","wheez","vomit","convulsion","unconscious")
conditions[["Hemorrhagic fever"]] <- c("fever","blood","bleed","skin")
conditions[["Other infection"]] <- c("fever","rash","convulsion","unconscious")
conditions[["Possible malaria"]] <- c("fever")
conditions[["Malnutrition"]] <- c("thin","swell")

# save(conditions, file="kalter.RData")
